/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--color-background))",
        accent: "hsl(var(--color-success))",
        textPearl: "hsl(var(--color-text))",
        mutedAsh: "hsl(var(--color-muted))",
        primary: {
          DEFAULT: "hsl(var(--color-primary))",
          hover: "hsl(var(--color-primary-hover))",
        },
        slateBorder: "hsla(var(--color-border) / 0.5)",
        secondary: "hsl(var(--color-secondary))",
        success: "hsl(var(--color-success))",
        warning: "hsl(var(--color-warning))",
        danger: "hsl(var(--color-danger))",
        info: "hsl(var(--color-info))",
        surface: "hsl(var(--color-surface))",
        brandTerracotta: "#E85D3F",
        brandCream: "#FFF8F2",
        brandWarmWhite: "#FFFCF9",
        brandCard: "#FFFFFF",
        brandTextDark: "#242424",
        brandTextMuted: "#6B6B6B",
        brandSuccess: "#22A06B",
        brandGold: "#F4B942",
        brandBorder: "#EEE7E1",
        // Kitchen Display System Warm Restaurant Operations Tokens
        kds: {
          bg: "#F7F4EE",
          surface: "#FFFFFF",
          sidebar: "#13241F",
          sidebarHover: "#1A312B",
          sidebarBorder: "#1E3B33",
          text: "#18201D",
          muted: "#6F746F",
          terracotta: "#C84A38",
          terracottaHover: "#B23F2F",
          mustard: "#D79A24",
          green: "#287A55",
          greenLight: "#E8F5EE",
          amber: "#C78A20",
          amberLight: "#FEF7EC",
          red: "#C7463A",
          redLight: "#FDEEEC",
          border: "#E3DED5",
          borderLight: "#ECE8E1",
          cardHover: "#FAFAF7",
        },
      },
      fontFamily: {
        sans: ["var(--font-sans)", "Inter", "sans-serif"],
        display: ["var(--font-display)", "Outfit", "sans-serif"],
        serif: ['"DM Serif Display"', "Libre Baskerville", "serif"],
      },
      boxShadow: {
        glass: "var(--elevation-glass)",
        kds: "0 2px 10px rgba(30, 30, 20, 0.06)",
        kdsHover: "0 4px 16px rgba(30, 30, 20, 0.09)",
      },
    },
  },
  plugins: [],
}
